{
  "formatVersion": "1.1",
  "component": {
    "group": "io.qameta.allure",
    "module": "allure-kotlin-commons",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "r5px5th7m5fidouswlebytlt3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.qameta.allure",
          "module": "allure-kotlin-model",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "allure-kotlin-commons-2.4.0.jar",
          "url": "allure-kotlin-commons-2.4.0.jar",
          "size": 151566,
          "sha512": "1e34016d4ed586322838852d76c8afbe83b2c721758594b7bd28e938c2a138c8d44747da08992c68e6cc669beaf94fdec63ebb64b4b5cce1e22220b297926def",
          "sha256": "5954e907e399dabfdaf2ea6f5f983ff21e7fa6b353e292fd28750a03c90c5442",
          "sha1": "7ece4d72bcaa7437ee41dd4b356ce21fab964826",
          "md5": "21b2788ab6014ccbef18df8fd048eb33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.qameta.allure",
          "module": "allure-kotlin-model",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "allure-kotlin-commons-2.4.0.jar",
          "url": "allure-kotlin-commons-2.4.0.jar",
          "size": 151566,
          "sha512": "1e34016d4ed586322838852d76c8afbe83b2c721758594b7bd28e938c2a138c8d44747da08992c68e6cc669beaf94fdec63ebb64b4b5cce1e22220b297926def",
          "sha256": "5954e907e399dabfdaf2ea6f5f983ff21e7fa6b353e292fd28750a03c90c5442",
          "sha1": "7ece4d72bcaa7437ee41dd4b356ce21fab964826",
          "md5": "21b2788ab6014ccbef18df8fd048eb33"
        }
      ]
    }
  ]
}
