{
  "formatVersion": "1.1",
  "component": {
    "group": "io.qameta.allure",
    "module": "allure-kotlin-model",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "r5px5th7m5fidouswlebytlt3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "allure-kotlin-model-2.4.0.jar",
          "url": "allure-kotlin-model-2.4.0.jar",
          "size": 74284,
          "sha512": "5891bccd24ff80365256fd41a780998dbf08ed98423f4cf5b7c4c0854e87b01bc33d1a12938f46ccae0130c941d18846b2bd4dc8b567cb250a53c2b3fe944d41",
          "sha256": "a9056c1452d0f93344c1c4f12db89c022b48fe6d14e8c9d2c9713f7c7e184dc8",
          "sha1": "6286bb0084f380865c6cbe6f8ca6706b69e7dab8",
          "md5": "702fc7ed326b07b5dd0884464273cc01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "allure-kotlin-model-2.4.0.jar",
          "url": "allure-kotlin-model-2.4.0.jar",
          "size": 74284,
          "sha512": "5891bccd24ff80365256fd41a780998dbf08ed98423f4cf5b7c4c0854e87b01bc33d1a12938f46ccae0130c941d18846b2bd4dc8b567cb250a53c2b3fe944d41",
          "sha256": "a9056c1452d0f93344c1c4f12db89c022b48fe6d14e8c9d2c9713f7c7e184dc8",
          "sha1": "6286bb0084f380865c6cbe6f8ca6706b69e7dab8",
          "md5": "702fc7ed326b07b5dd0884464273cc01"
        }
      ]
    }
  ]
}
