{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.5.2.aar",
          "url": "room-ktx-2.5.2.aar",
          "size": 32212,
          "sha512": "fe3bcef428a99961d6634d4c723d20009d2d8256c0ee025c5c261c078a8b861d5050458cd2e6fe3d2773c6db656ed5ef379b09080e5f822da4bb472ff4771a8b",
          "sha256": "70e193fb1dc5cf44fbe85fcd5f7181333b2c6b4944dcead0d311aa1cb03c503b",
          "sha1": "52b89016bf5cc54da92740481c94808ca32d74ec",
          "md5": "6f048371c36b9c9e8b8ed575632d1743"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.5.2.aar",
          "url": "room-ktx-2.5.2.aar",
          "size": 32212,
          "sha512": "fe3bcef428a99961d6634d4c723d20009d2d8256c0ee025c5c261c078a8b861d5050458cd2e6fe3d2773c6db656ed5ef379b09080e5f822da4bb472ff4771a8b",
          "sha256": "70e193fb1dc5cf44fbe85fcd5f7181333b2c6b4944dcead0d311aa1cb03c503b",
          "sha1": "52b89016bf5cc54da92740481c94808ca32d74ec",
          "md5": "6f048371c36b9c9e8b8ed575632d1743"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-ktx-2.5.2-sources.jar",
          "url": "room-ktx-2.5.2-sources.jar",
          "size": 6099,
          "sha512": "7f63f3a35847477b351b662dc954eb9a05645a56c888db67832185e6ca5f95c04efac285d3fc469c408e093b5575a7b863dae12d9c28557337bc878823357324",
          "sha256": "cd5aa1225bd0d063e6cb09a9256adad1b0b710a66b7c10f4768b7904a2df8e62",
          "sha1": "4f97d6d673bf28afbab26640145677da1febcfdf",
          "md5": "37f566507a47fb14352efbe6aefafcf2"
        }
      ]
    }
  ]
}